services:
  - type: web
    name: visiocar
    env: node
    plan: free
    buildCommand: npm install
    startCommand: ./start-on-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"